"""empty message

Revision ID: 2979731389a2
Revises: e06cf38affe1
Create Date: 2019-09-12 22:57:49.982070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2979731389a2'
down_revision = 'e06cf38affe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
