"""empty message

Revision ID: 565d95227c80
Revises: 2979731389a2
Create Date: 2019-09-12 23:12:26.568855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565d95227c80'
down_revision = '2979731389a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'users', ['password'], unique=True)
    # ### end Alembic commands ###
