"""empty message

Revision ID: 902250eddb7b
Revises: ef0bf173c222
Create Date: 2019-10-05 15:25:07.644325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '902250eddb7b'
down_revision = 'ef0bf173c222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership', sa.Column('card_cvv', sa.String(length=250), nullable=False))
    op.add_column('membership', sa.Column('card_expiration_date', sa.String(length=250), nullable=False))
    op.add_column('membership', sa.Column('card_holder_name', sa.String(length=120), nullable=False))
    op.add_column('membership', sa.Column('card_number', sa.String(length=250), nullable=False))
    op.add_column('membership', sa.Column('membership_name', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'membership', ['card_expiration_date'])
    op.create_unique_constraint(None, 'membership', ['card_number'])
    op.create_unique_constraint(None, 'membership', ['card_cvv'])
    op.drop_column('membership', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership', sa.Column('name', mysql.VARCHAR(length=250), nullable=False))
    op.drop_constraint(None, 'membership', type_='unique')
    op.drop_constraint(None, 'membership', type_='unique')
    op.drop_constraint(None, 'membership', type_='unique')
    op.drop_column('membership', 'membership_name')
    op.drop_column('membership', 'card_number')
    op.drop_column('membership', 'card_holder_name')
    op.drop_column('membership', 'card_expiration_date')
    op.drop_column('membership', 'card_cvv')
    # ### end Alembic commands ###
