"""empty message

Revision ID: e01ed2ed3e85
Revises: fbf1a3b1f356
Create Date: 2019-10-02 00:18:30.705481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01ed2ed3e85'
down_revision = 'fbf1a3b1f356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'membership', 'users', ['user_id'], ['id'])
    op.add_column('pictures', sa.Column('pic_folder', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pictures', 'pic_folder')
    op.drop_constraint(None, 'membership', type_='foreignkey')
    op.drop_column('membership', 'user_id')
    # ### end Alembic commands ###
