"""empty message

Revision ID: e06cf38affe1
Revises: 67e4820a8772
Create Date: 2019-09-12 22:35:12.686974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e06cf38affe1'
down_revision = '67e4820a8772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('first_name', table_name='users')
    op.drop_index('last_name', table_name='users')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=25), nullable=False))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False))
    op.create_index('last_name', 'users', ['last_name'], unique=True)
    op.create_index('first_name', 'users', ['first_name'], unique=True)
    # ### end Alembic commands ###
